=== Octoklingjs/CoursDeveloppement/XML/Atelier XML N°2/basefilms.dtd
<!ELEMENT basefilms (artistes+, films+)>
<!ELEMENT artistes (nom, categorie)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT categorie (#PCDATA)>
<!ELEMENT films (film+)>
<!ELEMENT film (titre, genre, annee, duree, acteurs, realisateur)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT duree (#PCDATA)>
<!ELEMENT acteurs (personne+)>
<!ELEMENT personne (#PCDATA)>
<!ELEMENT realisateur (#PCDATA)>

<!ATTLIST artiste codartiste ID #REQUIRED>

=== Octoklingjs/CoursDeveloppement/XML/Atelier XML N°2/basefilms.xml
<!DOCTYPE basefilms SYSTEM "basefilms.dtd" >
<basefilms>

	<artistes>
		<artiste codartiste="A">
	      	<nom>Peter Jackson</nom>
	    	<categorie>Réalisateur</categorie>
	   	</artiste>
	
	   	<artiste codartiste="B">
	   	   <nom>Chris Columbus</nom>
	   	   <categorie>Réalisateur</categorie>
	   	</artiste>
	
	   	<artiste codartiste="C">
	      	<nom>Jim Abrahams</nom>
	      	<categorie>Réalisateur</categorie>
	   	</artiste>
	</artistes>

   <films>
      <film>
         <titre>Le seigneur des anneaux</titre>

         <genre>Aventure</genre>

         <annee>2001</annee>

         <duree>180</duree>

         <acteurs>
            <personne>lan McKellen</personne>

            <personne>Liv Tyler</personne>
         </acteurs>

         <realisateur codartiste = "A"/>
      </film>

      <film>
         <titre>Maman, j'ai raté l'avion !</titre>

         <genre>Comédie</genre>

         <annee>1990</annee>

         <duree>103</duree>

         <acteurs>
            <personne>Macaulay Culkin</personne>

            <personne>Joe Pesci</personne>

            <personne>Daniel Stern</personne>
         </acteurs>

         <realisateur codartiste = "B"/>
      </film>

      <film>
         <titre>Hot Shots!</titre>

         <genre>Comédie</genre>

         <annee>1991</annee>

         <duree>84</duree>

         <acteurs>
            <personne>Charlie Sheen</personne>

            <personne>Valeria Golino</personne>

            <personne>Lloyd Bridges</personne>
         </acteurs>

         <realisateur codartiste = "C"/>
      </film>
   </films>
   
</basefilms>
